### ISSUE TITLE
uninitialized constant Onfleet::PermissionError (NameError)

### ISSUE THREAD

**Issue by jonathandean** [onfleet/ruby-onfleet#7]
NameError during attempt to retrieve the task list when auth permissions are incorrectly configured

```
gems/ruby-onfleet-1.0.2/lib/utils.rb:50:in `handle_api_error': uninitialized constant Onfleet::PermissionError (NameError)     

      raise PermissionError, "status: #{response.status}, message: #{response.body}"
```

**Comment by jonathandean** [comment]
a simple option seems to be adding these at the top of `utils.rb`

```ruby
require 'errors/http_error'
require 'errors/permission_error'
require 'errors/service_error'
```

It's a bit odd that the message comes back as html but that's another thing

```
 (Onfleet::PermissionError) gems/ruby-onfleet-1.0.2/lib/utils.rb:53:in `handle_api_error': status: 403, message: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

```

**Comment by jonathandean** [comment]
For reference this permission error was due to trying to access the staging environment endpoint. The same API key worked without specifying an endpoint and hence defaulting to the production API
